"""``hugr init`` - first-run wizard.

Output class: interactive (rejects --json with a pointer to a
machine-readable alternative; the wizard never makes sense in a
machine context because it prompts and writes files).

Behavior:

1. Confirm intent. Show what will be created and where.
2. Detect sources via hugr.sources.run_all().
3. Per component (yaams, cognitive-ledger, owa-piggy, owa-tools),
   classify into one of three states and prompt accordingly:
   - State A (binary missing): offer `brew install
     damsleth/tap/<formula>` [Y/n/skip]. On Y, install or abort the
     whole wizard if brew fails. On n/skip, defer.
   - State B (installed but no config): offer to chain the tool's
     own setup verb (yaams writes a generated config; `ledger init`;
     `owa-piggy setup --profile <alias> --email <email>` with
     interactive prompts for alias + email). owa-tools has no
     config of its own, so state B does not apply.
   - State C (installed + configured): reuse in place, no prompt.
4. Write the master ``$XDG_CONFIG_HOME/hugr/config.toml`` with the
   resolved tool paths and hugr-specific settings.
5. Run ``yaams setup``, ``yaams init-db``, ``yaams ingest --dry-run``
   if yaams is on PATH.
6. Print a deferred-items summary (if any) and three suggested next
   commands.

Idempotent: re-running probes again. The master config is overwritten
unless ``--force`` is omitted *and* the existing content is
unchanged; the user is prompted on conflict.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import time
from pathlib import Path
from typing import Any

import click

from hugr.config import (
  canonical_ledger_config,
  canonical_owa_piggy_config,
  canonical_yaams_config,
  config_dir,
  data_root_default,
  master_config_path,
  render_master,
)
from hugr.sources import ProbeResult, run_all, run_all_cached


def _existing_yaams_values(probes: list[ProbeResult]) -> dict:
  """Pull through values from a pre-existing standalone yaams config."""
  for p in probes:
    if p.name == "existing_yaams_config" and p.enabled:
      return p.extras.get("parsed") or {}
  return {}


def _build_yaams_config(probes: list[ProbeResult]) -> str:
  """Generate a yaams config seeded from probe results.

  Used only in the greenfield case (no ``~/.config/yaams/config.yaml``
  on disk). Schema mirrors yaams' own ``config.yaml.example``.
  """
  data = data_root_default()
  db_path = data / "yaams" / "data.db"
  by_name = {p.name: p for p in probes}

  def _probe(name: str) -> ProbeResult:
    return by_name.get(name, ProbeResult(name, False, "not probed"))

  imessage = _probe("imessage")
  email = _probe("email")
  signal = _probe("signal")
  github = _probe("github")
  notes = _probe("notes")
  tier2 = _probe("tier2_ledger")
  owa = _probe("owa_piggy")

  owa_profiles = owa.extras.get("profiles", []) if owa.enabled else []

  existing = _existing_yaams_values(probes)
  ex_ingest = (existing.get("ingest") or {}) if isinstance(existing, dict) else {}
  ex_email = ex_ingest.get("email") or {}
  ex_github = ex_ingest.get("github") or {}
  ex_notes = ex_ingest.get("notes") or {}
  ex_tier2 = ex_ingest.get("tier2_ledger") or {}
  ex_calendar = ex_ingest.get("calendar") or {}
  ex_teams = ex_ingest.get("teams") or {}

  github_username = ex_github.get("username") or github.extras.get("username") or ""
  user_addresses = ex_email.get("user_addresses") or []
  notes_vault = ex_notes.get("vault_path") or notes.extras.get("vault_path", "~/Documents/Obsidian")
  tier2_notes = ex_tier2.get("notes_path") or tier2.extras.get("notes_path", "~/.config/cognitive-ledger/notes")
  calendar_profiles = ex_calendar.get("profiles") or owa_profiles
  teams_profiles = ex_teams.get("profiles") or owa_profiles
  calendar_enabled = bool(ex_calendar.get("enabled")) if ex_calendar else False
  teams_enabled = bool(ex_teams.get("enabled")) if ex_teams else False

  def _bool(b: bool) -> str:
    return "true" if b else "false"

  def _hint_line(p: ProbeResult) -> str:
    if p.enabled:
      return f"# {p.reason}"
    if p.hint:
      return f"# disabled: {p.reason}\n    # hint: {p.hint}"
    return f"# disabled: {p.reason}"

  yaml = f"""# Generated by `hugr init` v{_hugr_version()}. Edit freely.
#
# `enabled: true/false` per source is the toggle. The other keys
# are tool-specific defaults the probe detected. Re-run `hugr init`
# any time to refresh detection (existing config is preserved
# unless you opt in to overwriting).

db_path: {db_path}

ingest:
  since: '2025-01-01T00:00:00Z'

  imessage:
    {_hint_line(imessage)}
    enabled: {_bool(imessage.enabled)}
    chat_db_path: {imessage.extras.get("chat_db_path", "~/Library/Messages/chat.db")}

  email:
    {_hint_line(email)}
    enabled: {_bool(email.enabled)}
    sources: {ex_email.get('sources') or []}   # add Apple Mail directories or .mbox files manually
    user_addresses: {user_addresses}

  signal:
    {_hint_line(signal)}
    enabled: {_bool(signal.enabled)}
    signal_dir: {signal.extras.get("signal_dir", "~/Library/Application Support/Signal")}
    include_attachments: true

  notes:
    {_hint_line(notes)}
    enabled: {_bool(notes.enabled or bool(ex_notes.get('enabled')))}
    vault_path: {notes_vault}

  tier2_ledger:
    {_hint_line(tier2)}
    enabled: {_bool(tier2.enabled or bool(ex_tier2.get('enabled')))}
    notes_path: {tier2_notes}

  github:
    {_hint_line(github)}
    enabled: {_bool(github.enabled)}
    username: '{github_username}'   # set your GitHub username here

  # Teams + calendar consume owa-piggy profiles. Add per-profile
  # blocks if you ingest Teams or calendar data.
  teams:
    enabled: {_bool(teams_enabled)}
    profiles: {teams_profiles}

  calendar:
    enabled: {_bool(calendar_enabled)}
    profiles: {calendar_profiles}

embed:
  model: BAAI/bge-m3
  dimension: 1024

entities:
  spacy_model: xx_ent_wiki_sm
  dictionary: []
"""
  return yaml


def _hugr_version() -> str:
  from hugr import __version__
  return __version__


def _yes(prompt: str, default: bool = True) -> bool:
  suffix = "[Y/n]" if default else "[y/N]"
  ans = click.prompt(f"{prompt} {suffix}", default="", show_default=False).strip().lower()
  if not ans:
    return default
  return ans in ("y", "yes")


def _three_way(prompt: str) -> str:
  """Y/n/skip prompt. Default Y. Returns 'yes', 'no', or 'skip'."""
  ans = click.prompt(f"{prompt} [Y/n/skip]", default="", show_default=False).strip().lower()
  if not ans:
    return "yes"
  if ans in ("y", "yes"):
    return "yes"
  if ans in ("s", "skip"):
    return "skip"
  return "no"


class BrewInstallFailed(Exception):
  """Raised when `brew install ...` returns nonzero. Caught at the
  top of `run()` to abort the wizard with a clean message."""

  def __init__(self, formula: str, returncode: int) -> None:
    super().__init__(f"brew install damsleth/tap/{formula} exited {returncode}")
    self.formula = formula
    self.returncode = returncode


_DEFERRED: list[str] = []


def _reset_deferred() -> None:
  _DEFERRED.clear()


def _defer(message: str) -> None:
  _DEFERRED.append(message)


def _prompt_install(binary: str, formula: str) -> bool:
  """State-A handling: if `binary` is missing, prompt to install.

  Returns True if the binary is on PATH after this call (already was,
  or brew install succeeded). Returns False if the user declined or
  skipped. Raises BrewInstallFailed if brew exited nonzero.
  """
  if shutil.which(binary):
    return True

  ans = _three_way(
    f"\n{binary} not installed. Install via `brew install damsleth/tap/{formula}`?"
  )
  if ans == "no":
    cmd = f"brew install damsleth/tap/{formula}"
    click.echo(f"  deferred. To install later: {cmd}")
    _defer(f"{binary:<14}  run: {cmd}")
    return False
  if ans == "skip":
    _defer(f"{binary:<14}  run: brew install damsleth/tap/{formula}")
    return False

  click.echo(f"  running: brew install damsleth/tap/{formula}")
  argv = ["brew", "install", f"damsleth/tap/{formula}"]
  try:
    result = subprocess.run(argv, capture_output=False)
  except FileNotFoundError as exc:
    raise BrewInstallFailed(formula, 127) from exc
  if result.returncode != 0:
    raise BrewInstallFailed(formula, result.returncode)
  if not shutil.which(binary):
    # brew claimed success but the binary still isn't on PATH; treat
    # as a failure rather than silently continue with state B.
    raise BrewInstallFailed(formula, -1)
  return True


def _print_probe_summary(probes: list[ProbeResult]) -> None:
  click.echo("\nSources detected:")
  for p in probes:
    if p.name == "existing_yaams_config":
      continue  # reported separately as a config-reuse prompt
    marker = "+" if p.enabled else "."
    click.echo(f"  {marker} {p.name:<16} {p.reason}")
    if not p.enabled and p.hint:
      click.echo(f"      hint: {p.hint}")


def _which_or_warn(binary: str) -> str | None:
  import shutil
  resolved = shutil.which(binary)
  if not resolved:
    click.echo(f"  ! {binary} not on PATH; skipping", err=True)
  return resolved


def _run_step(label: str, argv: list[str]) -> int:
  click.echo(f"\n-> {label}")
  result = subprocess.run(argv, capture_output=False)
  return result.returncode


def _run_quick_step(label: str, argv: list[str]) -> dict[str, Any]:
  started = time.monotonic()
  try:
    result = subprocess.run(argv, capture_output=True, text=True, check=False)
  except FileNotFoundError:
    return {
      "label": label,
      "argv": argv,
      "ok": False,
      "exit_code": 127,
      "duration_ms": int((time.monotonic() - started) * 1000),
      "stderr": "binary not on PATH",
    }
  return {
    "label": label,
    "argv": argv,
    "ok": result.returncode == 0,
    "exit_code": result.returncode,
    "duration_ms": int((time.monotonic() - started) * 1000),
    "stdout": result.stdout,
    "stderr": result.stderr,
  }


def _resolve_yaams_config(probes: list[ProbeResult], *, force: bool) -> Path | None:
  """Decide which yaams config path to record in the master config.

  Returns the resolved path, or None if the user declined to set one.
  Side effects: may run `brew install damsleth/tap/yaams` and may
  write ``~/.config/yaams/config.yaml`` in the greenfield case.
  """
  if not _prompt_install("yaams", "yaams"):
    return None

  canonical = canonical_yaams_config()
  if canonical.is_file():
    click.echo(f"+ yaams config already at {canonical}; reusing in place.")
    return canonical

  click.echo(f". no yaams config at {canonical}.")
  if not _yes("Generate one now from detected sources?", default=True):
    click.echo("  skipped; you can run `hugr init` again after creating one.")
    _defer("yaams         run: hugr init (then choose Y to generate config)")
    return None
  canonical.parent.mkdir(parents=True, exist_ok=True)
  canonical.write_text(_build_yaams_config(probes), encoding="utf-8")
  click.echo(f"  wrote {canonical}")
  return canonical


def _resolve_ledger_config() -> Path | None:
  if not _prompt_install("ledger", "cognitive-ledger"):
    return None

  canonical = canonical_ledger_config()
  if canonical.is_file():
    click.echo(f"+ cognitive-ledger config at {canonical}; reusing in place.")
    return canonical

  click.echo(f". no cognitive-ledger config at {canonical}.")
  if not _yes("Run `ledger init` now?", default=True):
    click.echo("  deferred. To set up later: ledger init")
    _defer("ledger        run: ledger init")
    return None
  ledger = shutil.which("ledger")
  if not ledger:
    _defer("ledger        run: ledger init")
    return None
  _run_step("ledger init", [ledger, "init"])
  return canonical if canonical.is_file() else None


def _resolve_owa_piggy_config() -> Path | None:
  if not _prompt_install("owa-piggy", "owa-piggy"):
    return None

  canonical = canonical_owa_piggy_config()
  if canonical.is_file():
    click.echo(f"+ owa-piggy config at {canonical}; reusing in place.")
    return canonical

  click.echo(f". no owa-piggy config at {canonical}.")
  if not _yes("Run `owa-piggy setup` now (prompts for alias + email)?", default=True):
    click.echo("  deferred. To set up later: owa-piggy setup --profile <alias> --email <email>")
    _defer("owa-piggy     run: owa-piggy setup --profile <alias> --email <email>")
    return None

  alias = click.prompt("  profile alias (e.g. work)", default="").strip()
  email = click.prompt("  email address", default="").strip()
  if not alias or not email:
    click.echo("  alias and email are both required; skipping owa-piggy setup.")
    _defer("owa-piggy     run: owa-piggy setup --profile <alias> --email <email>")
    return None
  owa_piggy = shutil.which("owa-piggy")
  if not owa_piggy:
    _defer("owa-piggy     run: owa-piggy setup --profile <alias> --email <email>")
    return None
  _run_step(
    "owa-piggy setup",
    [owa_piggy, "setup", "--profile", alias, "--email", email],
  )
  return canonical if canonical.is_file() else None


def _resolve_owa_tools_presence() -> bool:
  """owa-tools has no config of its own; just make sure the `owa`
  binary is on PATH (or installed via brew). Returns True if usable."""
  if not _prompt_install("owa", "owa-tools"):
    return False
  click.echo("+ owa-tools on PATH.")
  return True


def quick_bootstrap_doc(*, force: bool = False, with_models: bool = False) -> dict[str, Any]:
  started = time.monotonic()
  probes = run_all_cached()
  config_dir().mkdir(parents=True, exist_ok=True)
  data = data_root_default()
  data.mkdir(parents=True, exist_ok=True)

  writes: list[dict[str, Any]] = []
  adopted: dict[str, str] = {}
  hints: list[str] = []
  steps: list[dict[str, Any]] = []

  yaams_cfg = canonical_yaams_config()
  if yaams_cfg.is_file():
    adopted["yaams_config"] = str(yaams_cfg)
  else:
    yaams_cfg.parent.mkdir(parents=True, exist_ok=True)
    body = _build_yaams_config(probes)
    yaams_cfg.write_text(body, encoding="utf-8")
    writes.append({"path": str(yaams_cfg), "kind": "yaams_config"})

  ledger_cfg = canonical_ledger_config()
  ledger_path: Path | None = ledger_cfg if ledger_cfg.is_file() else None
  if ledger_path is not None:
    adopted["ledger_config"] = str(ledger_path)
  else:
    hints.append("ledger: run `ledger init`")

  owa_cfg = canonical_owa_piggy_config()
  owa_path: Path | None = owa_cfg if owa_cfg.is_file() else None
  if owa_path is not None:
    adopted["owa_piggy_config"] = str(owa_path)
  else:
    hints.append('auth: run "hugr auth setup"')

  master = master_config_path()
  master_body = render_master(
    version=_hugr_version(),
    data_root=data,
    yaams_config=yaams_cfg,
    ledger_config=ledger_path,
    owa_piggy_config=owa_path,
  )
  if force or not master.is_file() or master.read_text(encoding="utf-8") != master_body:
    master.parent.mkdir(parents=True, exist_ok=True)
    master.write_text(master_body, encoding="utf-8")
    writes.append({"path": str(master), "kind": "hugr_master_config"})

  yaams = shutil.which("yaams")
  if yaams:
    for label, argv in (
      ("yaams setup", [yaams, "setup", "--config", str(yaams_cfg)]),
      ("yaams init-db", [yaams, "init-db", "--config", str(yaams_cfg)]),
      ("yaams ingest --dry-run", [yaams, "ingest", "--dry-run", "--config", str(yaams_cfg)]),
    ):
      steps.append(_run_quick_step(label, argv))
  else:
    hints.append("yaams: not on PATH; skipped setup/init-db/dry-run")

  if not with_models:
    hints.append("models: skipped; pass `--with-models` for optional heavyweight setup")

  ok = all(step.get("ok") for step in steps) if steps else True
  doc = {
    "tool": "hugr",
    "version": _hugr_version(),
    "command": "init --quick",
    "ok": ok,
    "duration_ms": int((time.monotonic() - started) * 1000),
    "stats": {
      "probes": len(probes),
      "writes": writes,
      "adopted": adopted,
      "steps": steps,
      "with_models": with_models,
    },
    "warnings": hints,
    "error": None if ok else {
      "code": "bootstrap_step_failed",
      "message": "one or more quick bootstrap steps failed",
      "hint": "Inspect stats.steps for the failing command.",
    },
    "next_steps": [
      'hugr recall "what did we decide about ..."',
      "hugr inbox",
      "hugr auth setup",
    ],
  }

  return doc


def _quick_path(*, as_json: bool, force: bool = False, with_models: bool = False) -> int:
  doc = quick_bootstrap_doc(force=force, with_models=with_models)

  if as_json:
    click.echo(json.dumps(doc, ensure_ascii=False))
  else:
    click.echo("hugr init --quick")
    for item in writes:
      click.echo(f"  wrote {item['path']}")
    for key, path in adopted.items():
      click.echo(f"  adopted {key}: {path}")
    for step in steps:
      mark = "+" if step["ok"] else "x"
      click.echo(f"  {mark} {step['label']} (exit {step['exit_code']})")
    click.echo("\nNext steps:")
    for cmd in doc["next_steps"]:
      click.echo(f"  $ {cmd}")
  return 0 if doc.get("ok") else 5


def run(
  as_json: bool,
  *,
  force: bool = False,
  quick: bool = False,
  with_models: bool = False,
) -> int:
  if quick:
    return _quick_path(as_json=as_json, force=force, with_models=with_models)

  if as_json:
    click.echo(
      "hugr init is an interactive command; --json is rejected. "
      "Use `hugr init --quick --json` for headless bootstrap.",
      err=True,
    )
    return 1

  master = master_config_path()
  data = data_root_default()

  click.echo(f"hugr init v{_hugr_version()}")
  click.echo("This wizard:")
  click.echo("  1. probes for ingest sources")
  click.echo("  2. offers to install any missing components via brew")
  click.echo("  3. offers to run each component's own setup")
  click.echo(f"  4. writes {master}")
  click.echo(f"  5. uses {data} as the data root (override with HUGR_HOME)")
  if not _yes("\nContinue?"):
    click.echo("Aborted.")
    return 0

  _reset_deferred()

  # --- Detect ---------------------------------------------------------
  probes = run_all()
  _print_probe_summary(probes)

  # --- Resolve per-tool config paths ---------------------------------
  config_dir().mkdir(parents=True, exist_ok=True)
  data.mkdir(parents=True, exist_ok=True)

  try:
    yaams_cfg = _resolve_yaams_config(probes, force=force)
    ledger_cfg = _resolve_ledger_config()
    owa_cfg = _resolve_owa_piggy_config()
    _resolve_owa_tools_presence()
  except BrewInstallFailed as exc:
    click.echo(
      f"\nbrew install damsleth/tap/{exc.formula} failed (exit {exc.returncode}).\n"
      "Aborting `hugr init` - no master config was written.\n"
      "Check your brew tap, network, and re-run `hugr init` once the install works.",
      err=True,
    )
    return 5  # EXIT_RUNTIME per CONVENTIONS.md

  # --- Write master config -------------------------------------------
  body = render_master(
    version=_hugr_version(),
    data_root=data,
    yaams_config=yaams_cfg,
    ledger_config=ledger_cfg,
    owa_piggy_config=owa_cfg,
  )
  if master.is_file() and not force:
    existing_body = master.read_text(encoding="utf-8")
    if existing_body == body:
      click.echo(f"\n{master} already up to date.")
    else:
      click.echo(f"\nMaster config already exists at {master}")
      if not _yes("Overwrite?", default=False):
        click.echo("Keeping existing master config.")
      else:
        master.write_text(body, encoding="utf-8")
        click.echo(f"  wrote {master}")
  else:
    master.write_text(body, encoding="utf-8")
    click.echo(f"\nWrote {master}")

  # --- Run downstream setup ------------------------------------------
  if yaams_cfg is not None:
    yaams = _which_or_warn("yaams")
    if yaams:
      _run_step("yaams setup (install spaCy models if needed)", [yaams, "setup", "--config", str(yaams_cfg)])
      _run_step("yaams init-db", [yaams, "init-db", "--config", str(yaams_cfg)])
      _run_step("yaams ingest --dry-run", [yaams, "ingest", "--dry-run", "--config", str(yaams_cfg)])

  click.echo("\nhugr is configured.")
  if _DEFERRED:
    click.echo("\nDeferred:")
    for line in _DEFERRED:
      click.echo(f"  {line}")
    click.echo("\nRe-run `hugr init` after handling the above to wire them up.")

  click.echo("\nNext:")
  click.echo("  $ hugr doctor")
  click.echo("  $ hugr ingest")
  click.echo('  $ hugr recall "<question>"')
  return 0
